name: 'CodeQL'

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: '33 19 * * 1'
jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                language: ['javascript', 'typescript']
            steps:
                - uses: actions/checkout@v3
                - uses: actions/setup-node@v3
                  with:
                      node-version: 14

                - name: Initialize Code QL
                  uses: github/codeql-action/init@v2
                  with:
                      languages: ${{ matrix.language }}
                - name: Qutobuild
                  uses: github/codeql-action/autobuild@v2

                - name: Perform CodeQL Analysis
                  uses: github/codeql-action/analyze@v2
