name: simple-pagination

on:
    pull_request:
        branches: [master] # master 브랜치로 merge를 하게 될 때 action이 실행됨
jobs:
    continuous-integration:
        runs-on: ubuntu-latest # ubuntu 환경에서 실행됨
        steps: # line by line으로 실행됨
            - uses: actions/checkout@v3 # 다른 사람이 생성한 명령어 실행
            - uses: actions/checkout@v3
              with:
                  node-version: 16.x

            - name: Run Continuous Integration
              run: | # npm ci : package.json에 명시된 package install , package-lock과 package 비교,
                  npm ci 
                  npm test
